image: maven:3.5.4-jdk-8

services:
  - postgres:latest

variables:
  POSTGRES_DB: qieam
  POSTGRES_USER: gael
  POSTGRES_PASSWORD: ""
  SONAR_TOKEN: "4d04931fdfdc4c26d92cdca1de8b9749d3d57a06"
  SONAR_HOST_URL: "http://code-quality.argonaultes.com"
  GIT_DEPTH: 0

unit_test:
  stage: test
  script:
    - export DATABASE_URL_TEST=postgres://gael:@postgres:5432/qieam
    - mvn clean test
  except:
    - release

deploy_heroku:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/qieam-api.git
    - git push heroku +HEAD:release
  only:
    - release

deploy_heroku_dev:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/qieam-api-dev.git
    - git push heroku +HEAD:dev
  only:
    - dev

codequality:
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_request
    - master
