version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=JeremiGarotEpsi_qieam-back
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"

      - run: docker build -t $DOCKER_USER/qieam:latest .

      - run: docker push $DOCKER_USER/qieam:latest
      - run: ssh azureuser@40.115.3.23 "(docker stop qieam-back || true) && (docker rm -f qieam-back || true) && (docker run --rm --name qieam-back -d -p 4567:4567 gaelroustanepsi2022/qieam:latest)"

workflows:
  sample:
    jobs:
      - build-and-test
      - build-docker
    main:
      - build:
          context: SonarCloud
